# Exercises

1.  Describe how you would transfer a file from your local computer to the cluster. How would you download a file from online?

2.  Write a script that prints the following system information on Xanadu:

    -   Absolute path of your working directory
    -   OS name & version
    -   Current node
    -   CPUs
    -   Total memory

**Example:**

    -$ bash system_information.sh
    Working directory: /path/to/working
    OS name & version: Ubuntu 20.04
    Current node: xanadu-20
    CPUs: 40
    Total memory: 394849656 Kb

3.  What is the difference between an HPC and your local computer? Provide the memory and cpu specifications of your local computer.

4.  Write a script that changes the following text from lower case to upper case:

**Example:**

    -$ bash change_case.sh
    Enter any string in Lower Case: hello world
    Result: HELLO WORLD

5.  Write a script to determine which users are present on the system:

    > cguzman
    >
    > aakella
    >
    > mamee
    >
    > tchinta
    >
    > dhlee
    >
    > mmehta
    >
    > mlonga
    >
    > sderosa
    >
    > dcadman
    >
    > acowan

**Example:**

    -$ bash users.sh
    cguzman present
    aakella abset
    mamee present
    ...

6.  In the following working directory `/path/to/tbd`:
    1.  Display the contents of the directory

    2.  Enter the command `cd blah`, what happens?

    3.  Enter the command `cd ..`, what happens? (hint: use `pwd`)
7.  In the following working directory `/path/to/tbd`:
    1.  Use the `find` command to identify all files containing the word \`fasta'

    2.  What is the absolute path of the working directory? What is the relative path?
8.  Using the `vim` text editor, create a file called `username.txt` and write the following text:

<!-- -->

      Your name
      Your favorite color
      Your goals for this program

9.  Identify software packages that are most frequently used on the Xanadu cluster

    1.  Copy `cluster_software_usage.txt` into your working directory

    2.  Strip the version number from each software:

    **Example:**

        5630966|BioNetGen/2.5.0 => 5630966|BioNetGen

    3.  Count the unique instances of software and maintain order in the file list:

    **Example:**

    zlib occurs four times in the list

        3216|zlib/1.2.11 => 3216|zlib
        1|zlib/1.2.11xanadu-03 => 1|zlib
        1|zlib/1.2.11xanadu-50 => 1|zlib
        1|zlib/1.2.11xaxanadu-15 => 1|zlib

    and is used 3219 (3216+1+1+1) times:

        3219 zlib

10. Shorten fasta headers

    1.  Copy `Glycine_max.fasta` into your home directory

    2.  This protein file was downloaded from Phytozome.org. The sequence headers in this file look something like this:

    <!-- -->

        >Glyma.16G009500.2.p pacid=41077002 transcript=Glyma.16G009500.2 locus=Glyma.16G009500 ID=Glyma.16G009500.2.Wm82.a4.v1 annot-version=Wm82.a4.v1

    3.  Too long! Change the headers in Glycine_max.fasta so they display just the name or unique identifier of the protein sequences.

        becomes...

            >Glyma.16G009500.2.p

<!-- -->

11. How many module versions of `trinity` exist on Xanadu? What about `GATK`?
12. Copy the following bash script into your home directory: `/path/to/tbd`
    1.  Add your email to the header, and increase the memory to 5G

    2.  Module load the latest version of `fastqc` on the cluster

    3.  Submit the script with `sbatch` and check that it is running with `squeue`

    4.  What does the email notification say?

    5.  How do you know when the job is finished?

    6.  Were there any errors? How can you tell?

    7.  Display resource usage and efficiency of the completed job.
13. Try to go into another user home directory. How can you chance the permissions on your files?
